import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Navigation/SideBar";
import NavBar from "@/components/Navigation/NavBar";
import { ThemeProvider } from "@/context/ThemeContext";
import ThemeProviderWrapper from "@/components/ThemeProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <div className="overflow-x-clip min-h-[100vh]">
            <NavBar />
            <Sidebar />
            <div className="lg:p-8 p-4 lg:ml-[240px]">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
